# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-06-14 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=50, verbose_name='主題')),
                ('category', models.CharField(max_length=20, verbose_name='類別')),
                ('limit', models.CharField(max_length=10, verbose_name='權限')),
                ('introduce', models.CharField(max_length=90, verbose_name='簡介')),
                ('content', models.TextField(verbose_name='內容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
