# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-06-15 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20210614_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
